global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 10
   publish_frequency: 5
   width: 40.0
   height: 40.0
   resolution: 0.1
   static_map: true
   rolling_window: false
