local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 10
   publish_frequency: 5
   width: 20.0
   height: 20.0
   resolution: 0.1
   static_map: false
   rolling_window: true
